### ISSUE TITLE
Planned compatibility Spring Boot3.0?

### ISSUE THREAD

**Issue by kernelmix** [suchorski/springboot-keycloak-server#4]

**Comment by suchorski** [comment]
Hi. My plan is to keep Keycloak version up-to-date.

I have no plan to update SpringBoot to version 3 but I already tested it and checked one important thing. SpringBoot 3 uses the new libraries that uses jakarta.* instead of javax.* packages. So, when Keycloak update those libraries that use jakarta I'll try again to update the SpringBoot to version 3.
